
[project]
name = "ns3.40"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "matplotlib",
    "pandoc",
    "pdf2image",
    "pdfplumber",
    "pillow",
    "pypdf",
]

[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "cmake-build-extension>=0.4",
  "setuptools>=45",
  "setuptools_scm[toml]>=6.0",
  "wheel",
]

[tool.uv]
package = false

[tool.setuptools_scm]
local_scheme = "no-local-version"
version_scheme = "post-release"

[tool.cibuildwheel]
build-frontend = "build"

[dependency-groups]
dev = [
    "ruff>=0.17.0",
]
