
// clang-format off

#ifndef NS3_VERSION_DEFINES_H_
#define NS3_VERSION_DEFINES_H_



#cmakedefine NS3_VERSION_TAG "@NS3_VERSION_TAG@"

#cmakedefine NS3_VERSION_CLOSEST_TAG "@NS3_VERSION_CLOSEST_TAG@"

#define NS3_VERSION_MAJOR @NS3_VERSION_MAJOR@

#define NS3_VERSION_MINOR @NS3_VERSION_MINOR@

#define NS3_VERSION_PATCH @NS3_VERSION_PATCH@

#cmakedefine NS3_VERSION_RELEASE_CANDIDATE @NS3_VERSION_RELEASE_CANDIDATE@

#define NS3_VERSION_TAG_DISTANCE @NS3_VERSION_TAG_DISTANCE@

#cmakedefine NS3_VERSION_COMMIT_HASH "@NS3_VERSION_COMMIT_HASH@"

#cmakedefine01 NS3_VERSION_DIRTY_FLAG

#cmakedefine NS3_VERSION_BUILD_PROFILE "@NS3_VERSION_BUILD_PROFILE@"


#endif

// clang-format on
