
BriteConfig

BeginModel
	Name =  3
	N = 1000
	HS = 1000
	LS = 100
	NodePlacement = 1
	GrowthType = 1
	m = 2
	alpha = 0.15
	beta = 0.2
	BWDist = 1
	BWMin = 10.0
	BWMax = 1024.0
EndModel

BeginOutput
	BRITE = 1
	OTTER = 0
EndOutput
