#ifndef ARP_CACHE_H
#define ARP_CACHE_H

#include "ns3/address.h"
#include "ns3/callback.h"
#include "ns3/ipv4-address.h"
#include "ns3/net-device.h"
#include "ns3/nstime.h"
#include "ns3/object.h"
#include "ns3/output-stream-wrapper.h"
#include "ns3/packet.h"
#include "ns3/ptr.h"
#include "ns3/simulator.h"
#include "ns3/traced-callback.h"

#include <list>
#include <map>
#include <stdint.h>

namespace ns3 {

class NetDevice;
class Ipv4Interface;
class Ipv4Header;

class ArpCache : public Object {
public:
  static TypeId GetTypeId();
  class Entry;

  ArpCache();
  ~ArpCache() override;

  ArpCache(const ArpCache &) = delete;
  ArpCache &operator=(const ArpCache &) = delete;

  void SetDevice(Ptr<NetDevice> device, Ptr<Ipv4Interface> interface);
  Ptr<NetDevice> GetDevice() const;
  Ptr<Ipv4Interface> GetInterface() const;

  void SetAliveTimeout(Time aliveTimeout);
  void SetDeadTimeout(Time deadTimeout);
  void SetWaitReplyTimeout(Time waitReplyTimeout);

  Time GetAliveTimeout() const;
  Time GetDeadTimeout() const;
  Time GetWaitReplyTimeout() const;

  void SetArpRequestCallback(
      Callback<void, Ptr<const ArpCache>, Ipv4Address> arpRequestCallback);
  void StartWaitReplyTimer();
  ArpCache::Entry *Lookup(Ipv4Address destination);
  std::list<ArpCache::Entry *> LookupInverse(Address destination);
  ArpCache::Entry *Add(Ipv4Address to);
  void Remove(ArpCache::Entry *entry);
  void Flush();

  void PrintArpCache(Ptr<OutputStreamWrapper> stream);

  void RemoveAutoGeneratedEntries();

  typedef std::pair<Ptr<Packet>, Ipv4Header> Ipv4PayloadHeaderPair;

  class Entry {
  public:
    Entry(ArpCache *arp);

    void MarkDead();
    void MarkAlive(Address macAddress);
    void MarkWaitReply(Ipv4PayloadHeaderPair waiting);
    void MarkPermanent();
    void MarkAutoGenerated();
    bool UpdateWaitReply(Ipv4PayloadHeaderPair waiting);
    bool IsDead();
    bool IsAlive();
    bool IsWaitReply();
    bool IsPermanent();
    bool IsAutoGenerated();
    Address GetMacAddress() const;
    Ipv4Address GetIpv4Address() const;
    void SetMacAddress(Address macAddress);
    void SetIpv4Address(Ipv4Address destination);
    bool IsExpired() const;
    Ipv4PayloadHeaderPair DequeuePending();
    void ClearPendingPacket();
    uint32_t GetRetries() const;
    void IncrementRetries();
    void ClearRetries();

    void UpdateSeen();

  private:
    enum ArpCacheEntryState_e {
      ALIVE,
      WAIT_REPLY,
      DEAD,
      PERMANENT,
      STATIC_AUTOGENERATED
    };

    Time GetTimeout() const;

    ArpCache *m_arp;
    ArpCacheEntryState_e m_state;
    Time m_lastSeen;
    Address m_macAddress;
    Ipv4Address m_ipv4Address;
    std::list<Ipv4PayloadHeaderPair> m_pending;
    uint32_t m_retries;
  };

private:
  typedef std::map<Ipv4Address, ArpCache::Entry *> Cache;
  typedef std::map<Ipv4Address, ArpCache::Entry *>::iterator CacheI;

  void DoDispose() override;

  Ptr<NetDevice> m_device;
  Ptr<Ipv4Interface> m_interface;
  Time m_aliveTimeout;
  Time m_deadTimeout;
  Time m_waitReplyTimeout;
  EventId m_waitReplyTimer;
  Callback<void, Ptr<const ArpCache>, Ipv4Address> m_arpRequestCallback;
  uint32_t m_maxRetries;

  void HandleWaitReplyTimeout();
  uint32_t m_pendingQueueSize;
  Cache m_arpCache;
  TracedCallback<Ptr<const Packet>> m_dropTrace;
};

} // namespace ns3

#endif
