
#ifndef NEIGHBOR_CACHE_HELPER_H
#define NEIGHBOR_CACHE_HELPER_H

#include "ipv4-interface-container.h"
#include "ipv6-interface-container.h"

#include "ns3/arp-cache.h"
#include "ns3/arp-header.h"
#include "ns3/arp-l3-protocol.h"
#include "ns3/channel.h"
#include "ns3/icmpv6-l4-protocol.h"
#include "ns3/ipv4-address.h"
#include "ns3/ipv4-interface.h"
#include "ns3/ipv4-l3-protocol.h"
#include "ns3/ipv6-interface.h"
#include "ns3/ipv6-l3-protocol.h"
#include "ns3/net-device-container.h"
#include "ns3/node-list.h"

namespace ns3 {

class NeighborCacheHelper {
public:
  NeighborCacheHelper();
  ~NeighborCacheHelper();

  void PopulateNeighborCache();

  void PopulateNeighborCache(Ptr<Channel> channel) const;

  void PopulateNeighborCache(const NetDeviceContainer &c) const;

  void PopulateNeighborCache(const Ipv4InterfaceContainer &c) const;

  void PopulateNeighborCache(const Ipv6InterfaceContainer &c) const;

  void FlushAutoGenerated() const;

  void SetDynamicNeighborCache(bool enable);

private:
  void
  PopulateNeighborEntriesIpv4(Ptr<Ipv4Interface> ipv4Interface,
                              Ptr<Ipv4Interface> neighborDeviceInterface) const;

  void
  PopulateNeighborEntriesIpv6(Ptr<Ipv6Interface> ipv6Interface,
                              Ptr<Ipv6Interface> neighborDeviceInterface) const;

  void AddEntry(Ptr<Ipv4Interface> netDeviceInterface, Ipv4Address ipv4Address,
                Address macAddress) const;

  void AddEntry(Ptr<Ipv6Interface> netDeviceInterface, Ipv6Address ipv6Address,
                Address macAddress) const;

  void UpdateCacheByIpv4AddressRemoved(const Ptr<Ipv4Interface> interface,
                                       const Ipv4InterfaceAddress ifAddr) const;

  void UpdateCacheByIpv4AddressAdded(const Ptr<Ipv4Interface> interface,
                                     const Ipv4InterfaceAddress ifAddr) const;

  void UpdateCacheByIpv6AddressRemoved(const Ptr<Ipv6Interface> interface,
                                       const Ipv6InterfaceAddress ifAddr) const;

  void UpdateCacheByIpv6AddressAdded(const Ptr<Ipv6Interface> interface,
                                     const Ipv6InterfaceAddress ifAddr) const;

  bool m_globalNeighborCache{false};

  bool m_dynamicNeighborCache{false};
};

} // namespace ns3

#endif
